version: "3"
services:
  laravel-app:
    build:
      dockerfile: ./image/php-fpm/Dockerfile
      context: .
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/app
    environment:
      - APP_ENV="local"
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./image/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app
    links:
      - laravel-app
  front:
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: npm run watch-poll
